import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { trpc } from "../utils/trpc";
import Card, { ProductV2 } from "components/card";
import { NextPageWithLayout } from "./_app";
import { ReactElement, useEffect } from "react";
import Layout from "components/layout/layout";
import { ProductService } from "services/shopify/product.service";
import { GetServerSideProps } from "next";
import { PageService } from "services/contentful/page.service";
import {
  ContentfulService,
  GetHomePageQuery,
} from "services/contentful/contentful.service";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";

const inter = Inter({ subsets: ["latin"] });

interface Props {
  products?: ProductService.List;
  homePageInfo: GetHomePageQuery;
}

export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  const products = await ProductService.getList();
  //console.log(products);
  const homePageInfo = await PageService.getHomePage();
  const title = await ContentfulService.getHomePageTitle();

  return {
    props: {
      products,
      homePageInfo,
      title,
    },
  };
};

const Home: NextPageWithLayout<Props> = ({ products, homePageInfo }) => {
  // const { data, isLoading } = trpc.hello.useQuery({ text: "client" });

  const homePage = homePageInfo?.homePage;
  //const productsOld = data.products as ProductV2[];
  if (!homePage) return <></>;
  console.log(homePage?.description);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline flex justify-center">
        <p>{homePage?.title}</p>
      </h1>
      {documentToReactComponents(homePage?.description?.json)}

      <div className="mx-12 mt-12 grid grid-cols-3 gap-4 justify-center">
        {products?.products.map((product) => (
          <Card key={product.id} product={product} />
        ))}
      </div>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
